# LIBRERIA NUMPY

para poder trabjar con numpy, es necesario la importacion de una libreria que se llama de la misma manera
la importacion de dicha libreria se hace de la siguiente manera

### Importacion de librerias

In [24]:
import math
import numpy as np 

## Ejercicio 1.0 --> producto matricial, matriz determinante y matriz transpuesta

In [12]:
### CREACION DE MATRICES ###
matriz_1 = np.array([[1,2],[3,4]])
matriz_2 = np.array([[5,6],[7,8]])

prod_matricial = np.matmul(matriz_1,matriz_2)
determinante_1 = np.linalg.det(matriz_1)
determinante_2 = np.linalg.det(matriz_2)
transpuesta_1 = np.transpose(matriz_1)
transpuesta_2 = np.transpose(matriz_2)

print(prod_matricial)
print("\n---------------\n")
print(determinante_1)
print("\n---------------\n")
print(determinante_2)
print("\n---------------\n")
print(transpuesta_1)
print("\n---------------\n")
print(transpuesta_2)

[[19 22]
 [43 50]]

---------------

-2.0000000000000004

---------------

-1.999999999999999

---------------

[[1 3]
 [2 4]]

---------------

[[5 7]
 [6 8]]


## Ejercicio 1.1 --> Resolucion de ecuaciones lineales

numpy tiene una funcion que permite solucionar ecuaciones lineales que se ecuentran de manera implisita.
suponiendo que tenemos las siguientes ecuaciones

2X + 3y = 5

4X - y = 2

De estas dos ecueaciones tenemos 2 array 

array_coeficiones = ([[2,3],[4,-1]])

array_constantes = ([5,2])

In [7]:
coeficientes = ([[2,3],[4,-1]])
constantes = ([5,2])

resolucion = np.linalg.solve(coeficientes, constantes)

print ("El valor de X es --> ",resolucion[0])
print ("El valor de y es -->",resolucion[1])

El valor de X es -->  0.7857142857142857
El valor de y es --> 1.1428571428571428


## Ejercicio 1.2 --> obtenemos informacion de un array multidimencional

In [14]:
array_1 = ([[[0,1,2,3],[4,5,6,7]],
           [[8,9,10,11],[12,13,14,15]],
           [[16,17,18,19],[20,21,22,23]]])

Si queremos saber cual es la dimencion del array, utilizamos la siguiente funcion

In [15]:
dimencion = np.ndim(array_1)
print(dimencion)

3


Si queremos saber cual es la cantidad total de elementos, sin importar la dimencion, utilizamos la siguiente funcion

In [16]:
elementos = np.size(array_1)
print(elementos)

24


Si queremos saber la estructura del array, es decir cuantos en z, en y y en x; utilizamos la siguiente funcion

In [17]:
estructura = np.shape(array_1)
print(estructura)

(3, 2, 4)


## Ejercicio 1.3 --> como obtener valores de un array

In [1]:
array_2 = ([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

Recordando que el primer elemento es siempre el 0, teniendo un total de 20 numero, sabemos que va desde el 0 al 19.
para poder obtener e valor de una posicion particular se hace de la siguiente manera.

In [2]:
print(array_2[4]) #de esta manera obtenemos el valor de la posicion 4 q es el valor 5

5


si querenis ibtener un rango de posiciones, lo que se hace es lo siguiente

In [7]:
print(array_2[0:4]) #de esta manera obtenemos los valores de las posiciones desde la posicion 0 hasta la 3 (una menos de la indicada)

[1, 2, 3, 4]


si uno no coloca el primer numero en el caso anterior, toma como si estuviese el cero y si no se coloca el ultimo numero, toma como si estuviese el ultimo

In [8]:
print(array_2[:5])

[1, 2, 3, 4, 5]


In [9]:
print(array_2[4:])

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


Si colocamos numero negativos desde el -1 en adelante, recorremos el array de atras para adelante.

Es decir que si ponemos -1, obtendremos el 20

In [10]:
print(array_2[-1])

20


In [17]:
print(array_2[-5:-1])

[16, 17, 18, 19]


## Ejercicio 1.4 --> ordenar un array, lo cual se hace de la siguiente manera

In [25]:
array_desordenado = [5,7,2,4,1,9,8,3,6]
array_ordenado = np.sort(array_desordenado)
print(array_ordenado)

[1 2 3 4 5 6 7 8 9]


tambien es posible dar vuelta el array llevando el primer elemento al ultimo y el ultimo al primero

esto se realiza de la siguiente manera

In [27]:
array_ordenado_rotado = np.flip(array_ordenado)
print(array_ordenado_rotado)

[9 8 7 6 5 4 3 2 1]


## Ejercicio 1.5 --> Generacion de array con valores random

In [42]:
rng = np.random.default_rng()

para generar un arran con valores radom que van desde 0 sin incluirlo hasta 1 incluido, se hace lo siguiente

In [47]:
array_random = rng.random(size = (3,5)) # crea un array con 3 valores que van entre 0 no tomado hasta 1 si considerado
print(array_random)

[[0.44923041 0.20659867 0.03818238 0.37506566 0.44170292]
 [0.35645967 0.27054911 0.58603726 0.36813599 0.74240525]
 [0.60052693 0.19307663 0.69389608 0.34099067 0.81512397]]


para generar un array con valores enteros con maximo y minimo, se hace de la siguiente manera

In [40]:
array_random_entero = rng.integers(low = 5,high = 10,size=(4,4))
print(array_random_entero)

[[7 9 9 5]
 [5 9 9 9]
 [9 8 6 5]
 [9 6 9 9]]


## Ejercicio 1.6 --> obtener los valores unicos en otro array

In [41]:
array_largo = [1,4,3,6,8,6,5,4,2,3,5,8,9,7,6,5,4,3,7,9,8,7,8,6,1,3,2,5,6,8,9,8,7,6,7,5,4,3,1,5,6,7,9,8,4,3,2,5]
valores_unicos = np.unique(array_largo)
print(valores_unicos)

[1 2 3 4 5 6 7 8 9]


## Ejercicio 1.7 --> calcular valores estadisticos

In [50]:
array_ran = rng.integers(size = 20, low = 1, high = 10000)
print(array_ran)

[5110 8401 3802 1141  883 6582 8080 1148 3904 7109 8117 3563 8765 4626
 8505 1074 2054 8432 1610 1871]


Calculamos desviacion estandar

In [52]:
des_estandar = np.std(array_ran)
print(des_estandar)

2928.330194411142


Calculamos la media

In [54]:
media = np.mean(array_ran)
print(media)

4738.85


Obtenemos valor maximo y minimo

In [55]:
val_max = np.max(array_ran)
val_min = np.min(array_ran)
print("El valor maximo es --> ",val_max)
print("El valor minimo es --> ",val_min)

El valor maximo es -->  8765
El valor minimo es -->  883
